# Brand-swap script for fork-and-rebrand workflow.
# Reads parameters, then mutates the four files a maker needs to change
# to make this template their own. Idempotent — safe to run multiple
# times. Does NOT bump manifest version (do that explicitly with
# Update-ManifestVersion when you're ready to publish).
#
# Usage:
#   ./scripts/swap-brand.ps1 `
#     -CsEnvId 61453fde-... `
#     -CsSchema ksteam_ak001 `
#     -TenantId 301759bc-... `
#     -AgentName "Acme Analyst" `
#     -AccentColor "#003399" `
#     -LogoText "A"
#
# Documented in docs/QUICK-START.md.

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $CsEnvId,
    [Parameter(Mandatory)] [string] $CsSchema,
    [Parameter(Mandatory)] [string] $TenantId,
    [Parameter(Mandatory)] [string] $AgentName,
    [Parameter()] [string] $AccentColor = "#003399",
    [Parameter()] [string] $AccentForeground = "#ffffff",
    [Parameter()] [string] $LogoText = "A",
    [Parameter()] [string] $CompanyName = "Contoso",
    [Parameter()] [string] $RepoRoot = (Resolve-Path "$PSScriptRoot/..").Path
)

$ErrorActionPreference = 'Stop'

function Edit-File($path, $scriptBlock) {
    $full = Join-Path $RepoRoot $path
    if (-not (Test-Path $full)) {
        Write-Warning "skip (not found): $path"
        return
    }
    $content = Get-Content $full -Raw
    $next = & $scriptBlock $content
    if ($next -ne $content) {
        $next | Set-Content -NoNewline -Encoding UTF8 $full
        Write-Host "wrote $path"
    } else {
        Write-Host "nochange $path"
    }
}

# 1. mcp-server/src/config.ts — defaults for csEnvId, csSchema, agentName.
Edit-File 'mcp-server/src/config.ts' {
    param($c)
    $c = $c -replace "(required\(\s*'CS_ENV_ID',\s*')[^']*('\s*\))", ('${1}' + $CsEnvId + '${2}')
    $c = $c -replace "(required\(\s*'CS_SCHEMA',\s*')[^']*('\s*\))", ('${1}' + $CsSchema + '${2}')
    $c = $c -replace "(required\(\s*'AGENT_NAME',\s*')[^']*('\s*\))", ('${1}' + $AgentName + '${2}')
    return $c
}

# 2. webchat-ui/.env — brand vars consumed by Vite at build time.
$envPath = Join-Path $RepoRoot 'webchat-ui/.env'
$envText = @"
# Auto-generated by scripts/swap-brand.ps1.
# Edit by re-running the script, not by hand.
VITE_BRAND_AGENT_NAME=$AgentName
VITE_BRAND_COMPANY_NAME=$CompanyName
VITE_BRAND_LOGO_TEXT=$LogoText
VITE_BRAND_ACCENT_COLOR=$AccentColor
VITE_BRAND_ACCENT_FOREGROUND=$AccentForeground
VITE_CS_ENVIRONMENT_ID=$CsEnvId
VITE_CS_SCHEMA_NAME=$CsSchema
VITE_CS_TENANT_ID=$TenantId
"@
$envText | Set-Content -NoNewline -Encoding UTF8 $envPath
Write-Host "wrote webchat-ui/.env"

# 3. declarative-agent/appPackage/manifest.json — name + developer fields.
Edit-File 'declarative-agent/appPackage/manifest.json' {
    param($c)
    # Replace top-level name.short / name.full strings only when they
    # match the placeholder. Lets repeat runs be idempotent — won't
    # blast over a maker's hand-edits.
    $c = $c -replace '("name"\s*:\s*\{\s*"short"\s*:\s*")[^"]*(",\s*"full"\s*:\s*")[^"]*(")',
        ('${1}' + $AgentName + '${2}' + $AgentName + ' for Microsoft 365 Copilot${3}')
    return $c
}

# 4. declarative-agent/appPackage/declarativeAgent.json — name + description.
Edit-File 'declarative-agent/appPackage/declarativeAgent.json' {
    param($c)
    $c = $c -replace '("name"\s*:\s*")[^"]*(")', ('${1}' + $AgentName + '${2}')
    $c = $c -replace '("description"\s*:\s*")[^"]*(")',
        ('${1}Embeds the ' + $AgentName + ' Copilot Studio agent inside Microsoft 365 Copilot as a UI widget.${2}')
    return $c
}

Write-Host ""
Write-Host "Done. Next steps:"
Write-Host "  1. Run 'azd up' to provision Azure resources"
Write-Host "  2. Configure Entra SSO (see docs/QUICK-START.md step 5)"
Write-Host "  3. Run 'teamsapp publish --env dev' from declarative-agent/"
